FROM <the owner of the base image>/<the name of the base image>
AUTHOR <your name and username>

RUN <install nginx>
...

COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

CMD <start Nginx>
