#!/bin/bash
echo """
Welcome to the team! We look forward to your contributions to this awesome but nameless Python application!

1. To start developing this Python server, please use these steps:

    npm install --global please-runner
    please run

2. Feel free to make changes in the code – the app will auto reload! ✨

3. Whenever you change your dependencies in requirements.txt, please use these steps:

    # kill your \`please run\`
    please build
    please run again
"""
