#!/bin/bash -e
project_root="$(dirname "$(dirname "$(readlink -f "$0")")")"

if ! \
  docker images \
  | grep -q -E '^the-next-big-flask-thing\b'
then
  scripts/build
fi

# This is where the Docker container that we can develop on gets run
docker run \
  --rm \
  --tty \
  --interactive \
  --volume "$project_root"/src:/the-next-big-flask-thing/src \
  --publish 9000:5000 \
  the-next-big-flask-thing
