FROM <a chosen operating system image, choose a specific version!>
MAINTAINER <your name and username>

WORKDIR /app

COPY <some stuff> <to some location inside the container>

RUN <do you need to install something?>

CMD <run the Python app in the foreground>
